(import (srfi srfi-64) (thinker app) (thinker data connective) (thinker data primitive) (thinker data expand))

(test-begin "app")
(define thinker (make-thinker))
(thinker 'add '(and "A" (or "B" (not "C"))))
(thinker 'add "A")
(test-assert (equal? '("B" "C" "A") (thinker 'list-prims)))
(thinker 'remove 0)
(test-assert (equal? (thinker 'list) '((and "A" (or "B" (not "C"))))))
(test-assert (thinker 'entails? "A"))
(test-assert (not (thinker 'entails? "B")))
(thinker 'add '(not "B"))
(test-assert (thinker 'entails? '(not "C")))
(thinker 'clear)
(test-assert (null? (thinker 'list)))
(install-connective! '=> (lambda (A B) `(or (not ,(expand-proposition A)) ,(expand-proposition B))))
(install-connective! '<=> (lambda (A B) `(and (=> ,A ,B) (=> ,B ,A))))
(test-assert (or (equal? '(and or not <=> =>) (thinker 'list-conns)) (equal? '(and or not => <=>) (thinker 'list-conns))))
(thinker 'add '(=> "a" (not "b")))
(test-assert (equal? (thinker 'list) '((or (not "a") (not "b")))))
(thinker 'clear)
(thinker 'add '(<=> "a" "b"))
(test-assert (equal? (thinker 'list) '((and (or (not "a") "b") (or (not "b") "a")))))
(test-end "app")