(import (srfi srfi-64) (app) (data connective) (data primitive))

(test-begin "app")
(define thinker (make-thinker))
(thinker 'lock)
(thinker 'add '(and "A" (or "B" (not "C"))))
(thinker 'add "A")
(thinker 'remove 0)
(test-assert (equal? (thinker 'list) '((and "A" (or "B" (not "C"))))))
(test-assert (thinker 'entails? "A"))
(test-assert (not (thinker 'entails? "B")))
(thinker 'add '(not "B"))
(test-assert (thinker 'entails? '(not "C")))
(thinker 'clear)
(test-assert (null? (thinker 'list)))
(thinker 'unlock)
(test-end "app")