(import (srfi srfi-64) (app) (data connective) (data primitive) (expander expand))

(test-begin "app")
(define thinker (make-thinker))
(thinker 'add '(and "A" (or "B" (not "C"))))
(thinker 'add "A")
(test-assert (equal? '("B" "C" "A") (thinker 'list-prims)))
(thinker 'remove 0)
(test-assert (equal? (thinker 'list) '((and "A" (or "B" (not "C"))))))
(test-assert (thinker 'entails? "A"))
(test-assert (not (thinker 'entails? "B")))
(thinker 'add '(not "B"))
(test-assert (thinker 'entails? '(not "C")))
(thinker 'clear)
(test-assert (null? (thinker 'list)))
(install-connective! '=> (lambda (A B) `(or (not ,A) ,B)))
(thinker 'add '(=> "a" "b"))
(test-assert (equal? (thinker 'list) '((or (not "a") "b"))))
(test-end "app")