(import (thinker data connective) (thinker data primitive) (srfi srfi-64) (thinker exn contract) (thinker exn internal))

(test-begin "data")
(define p1 (Prim "p1"))
(define p2 (Prim "p2"))
(define v (& (|| p1 p2) (! (|| p1 p2))))
(test-assert (and? v))
(test-assert (= 2 (length (children v))))
(test-assert (or? (car (children v))))
(test-assert (not? (cadr (children v))))
(test-error &contract-error (children 1))
(test-error &contract-error (Prim 1))
(test-error &contract-error (& 1))
(test-end "data")
