(import (srfi srfi-64) (thinker data expand) (srfi srfi-69))

(test-begin "expand")
(install-connective! '=> (lambda (a b) `(or (not ,(expand-proposition a)) ,(expand-proposition b))))
(install-connective! '- (lambda (_) 1))
(test-assert (equal? '(or (not "a") "b") (expand-proposition '(=> "a" "b"))))
(test-error &exception (install-connective! 'and (lambda () "")))
(test-error &exception (expand-proposition '(<=> "A" "B")))
(test-error &exception (expand-proposition '(- "A")))
(test-end "expand")