(library (algo parse)
    (export parse-tree)
    (import (ice-9 match) 
            (data connective) 
            (data primitive)
            (exn contract)
            (rnrs (6)))
    
    (define (parse-tree t)
        (let loop ((t t))
            (match t
                ((? string? v) (Prim v))
                (('and cs ...)
                 (apply & (map loop cs)))
                (('or cs ...)
                 (apply || (map loop cs)))
                (('not c)
                 (! (loop c)))
                (_ (raise-contract-error 'parse-tree "(recursive/c t (or/c string? (cons/c (or/c 'and 'or 'not) (listof t))))" t))))))