(library (algo pkg)
    (export make-pkg-manager)
    (import (rnrs (6)) (srfi srfi-69) (srfi srfi-28) (exn contract) (exn internal) (ice-9 threads))
    
    (define (make-pkg-manager)
        (define table (make-hash-table eq?))
        (define mutex (make-mutex))
    
        (define (install! name value)
            (unless (symbol? name)
                (raise-contract-error 'install! "symbol?" name))
            (dynamic-wind 
                (lambda () (lock-mutex mutex))
                (lambda () 
                    (if (hash-table-exists? table name)
                        (raise-internal-error 'install! (format "name ~s has already been installed" name)))
                    (hash-table-set! table name value))
                (lambda () (unlock-mutex mutex))))
        (define (get name)
            (unless (symbol? name)
                (raise-contract-error 'get "symbol?" name))
            (unless (hash-table-exists? table name)
                (raise-internal-error 'get (format "name ~s not found" name)))
            (hash-table-ref table name))
        (define (has? name)
            (unless (symbol? name)
                (raise-contract-error 'has? "symbol?" name))
            (hash-table-exists? table name))
        (values install! get has?)))